CREATE USER a01702686 IDENTIFIED BY password123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS
PROFILE DEFAULT;
-- Otorgar permisos a A01702686, de la misma
GRANT ALUMNO TO a01702686;
-- Asignar el rol default al usuario
ALTER USER a01702686 DEFAULT ROLE ALL;
--------------------------------------------------------
--  DDL for Table CIUDAD
--------------------------------------------------------

  CREATE TABLE "A01702686"."CIUDAD" 
   (	"ID" NUMBER, 
	"CODIGO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOMBRE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "A01702686"."CLIENTE" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOS" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"TITULO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FECHA_NACIMIENTO" DATE, 
	"CALLE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CP" NUMBER, 
	"NUMERO" NUMBER, 
	"COLONIA" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CIUDAD" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONO" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "A01702686"."CUENTA" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_SUCURSAL" NUMBER, 
	"ID_TIPOCUENTA" NUMBER, 
	"SALDO" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "A01702686"."EMPLEADO" 
   (	"ID" NUMBER, 
	"ID_SUCURSAL" NUMBER, 
	"CP" NUMBER, 
	"CALLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"COLONIA" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CIUDAD" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMERO" NUMBER, 
	"TITULO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FECHA_NACIMIENTO" DATE, 
	"NOMBRE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOS" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONO" NUMBER, 
	"ID_TIPOEMPLEADO" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "A01702686"."MOVIMIENTO" 
   (	"ID" NUMBER, 
	"FECHA" DATE, 
	"TIPO_MOVIMIENTO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_CUENTA" NUMBER, 
	"MONTO" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "A01702686"."SUCURSAL" 
   (	"ID" NUMBER, 
	"COLONIA" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CP" NUMBER, 
	"TELEFONO" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMERO" NUMBER, 
	"ID_CIUDAD" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TASA_CAMBIO
--------------------------------------------------------

  CREATE TABLE "A01702686"."TASA_CAMBIO" 
   (	"ID" NUMBER, 
	"CODIGO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"VALOR" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_CUENTA
--------------------------------------------------------

  CREATE TABLE "A01702686"."TIPO_CUENTA" 
   (	"ID" NUMBER, 
	"COMISION" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "A01702686"."TIPO_EMPLEADO" 
   (	"ID" NUMBER, 
	"PERMISOS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUELDO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into A01702686.CIUDAD
SET DEFINE OFF;
REM INSERTING into A01702686.CLIENTE
SET DEFINE OFF;
REM INSERTING into A01702686.CUENTA
SET DEFINE OFF;
REM INSERTING into A01702686.EMPLEADO
SET DEFINE OFF;
REM INSERTING into A01702686.MOVIMIENTO
SET DEFINE OFF;
REM INSERTING into A01702686.SUCURSAL
SET DEFINE OFF;
REM INSERTING into A01702686.TASA_CAMBIO
SET DEFINE OFF;
REM INSERTING into A01702686.TIPO_CUENTA
SET DEFINE OFF;
REM INSERTING into A01702686.TIPO_EMPLEADO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOVIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."MOVIMIENTO_PK" ON "A01702686"."MOVIMIENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."CUENTA_PK" ON "A01702686"."CUENTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TASA_CAMBIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."TASA_CAMBIO_PK" ON "A01702686"."TASA_CAMBIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."CLIENTE_PK" ON "A01702686"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."TIPO_EMPLEADO_PK" ON "A01702686"."TIPO_EMPLEADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUCURSAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."SUCURSAL_PK" ON "A01702686"."SUCURSAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."EMPLEADO_PK" ON "A01702686"."EMPLEADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."TIPO_CUENTA_PK" ON "A01702686"."TIPO_CUENTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A01702686"."CIUDAD_PK" ON "A01702686"."CIUDAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "A01702686"."CUENTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CUENTA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CUENTA" MODIFY ("ID_TIPOCUENTA" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CUENTA" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CUENTA" ADD CONSTRAINT "CUENTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "A01702686"."CUENTA" MODIFY ("SALDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TASA_CAMBIO
--------------------------------------------------------

  ALTER TABLE "A01702686"."TASA_CAMBIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TASA_CAMBIO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TASA_CAMBIO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TASA_CAMBIO" ADD CONSTRAINT "TASA_CAMBIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "A01702686"."TIPO_EMPLEADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_EMPLEADO" MODIFY ("PERMISOS" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_EMPLEADO" MODIFY ("SUELDO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_EMPLEADO" ADD CONSTRAINT "TIPO_EMPLEADO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("CP" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("CALLE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "A01702686"."EMPLEADO" MODIFY ("ID_TIPOEMPLEADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIUDAD
--------------------------------------------------------

  ALTER TABLE "A01702686"."CIUDAD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CIUDAD" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CIUDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CIUDAD" ADD CONSTRAINT "CIUDAD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("CP" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("CALLE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."SUCURSAL" ADD CONSTRAINT "SUCURSAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "A01702686"."SUCURSAL" MODIFY ("TELEFONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("CALLE" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("CP" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIMIENTO
--------------------------------------------------------

  ALTER TABLE "A01702686"."MOVIMIENTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."MOVIMIENTO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."MOVIMIENTO" MODIFY ("TIPO_MOVIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."MOVIMIENTO" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."MOVIMIENTO" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."MOVIMIENTO" ADD CONSTRAINT "MOVIMIENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_CUENTA
--------------------------------------------------------

  ALTER TABLE "A01702686"."TIPO_CUENTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_CUENTA" ADD CONSTRAINT "TIPO_CUENTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "A01702686"."TIPO_CUENTA" MODIFY ("COMISION" NOT NULL ENABLE);
  ALTER TABLE "A01702686"."TIPO_CUENTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "A01702686"."CUENTA" ADD CONSTRAINT "CUENTA_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "A01702686"."CLIENTE" ("ID") ENABLE;
  ALTER TABLE "A01702686"."CUENTA" ADD CONSTRAINT "CUENTA_FK2" FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "A01702686"."SUCURSAL" ("ID") ENABLE;
  ALTER TABLE "A01702686"."CUENTA" ADD CONSTRAINT "CUENTA_FK3" FOREIGN KEY ("ID_TIPOCUENTA")
	  REFERENCES "A01702686"."TIPO_CUENTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "A01702686"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_FK1" FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "A01702686"."SUCURSAL" ("ID") ENABLE;
  ALTER TABLE "A01702686"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_FK2" FOREIGN KEY ("ID_TIPOEMPLEADO")
	  REFERENCES "A01702686"."TIPO_EMPLEADO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTO
--------------------------------------------------------

  ALTER TABLE "A01702686"."MOVIMIENTO" ADD CONSTRAINT "MOVIMIENTO_FK1" FOREIGN KEY ("ID_CUENTA")
	  REFERENCES "A01702686"."CUENTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "A01702686"."SUCURSAL" ADD CONSTRAINT "SUCURSAL_FK1" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "A01702686"."CIUDAD" ("ID") ENABLE;